export type MenuItem =
  | { type: "item"; label: string; shortcut?: string; disabled?: boolean }
  | { type: "separator" }
  | { type: "submenu"; label: string };

export const MENUS: Record<string, MenuItem[]> = {
  File: [
    { type: "item", label: "New Text File", shortcut: "Ctrl+N" },
    { type: "item", label: "New Window", shortcut: "Ctrl+Shift+N" },
    { type: "separator" },
    { type: "item", label: "Open File...", shortcut: "Ctrl+O" },
    { type: "item", label: "Open Folder...", shortcut: "Ctrl+K Ctrl+O" },
    { type: "submenu", label: "Open Recent" },
    { type: "separator" },
    { type: "item", label: "Save", shortcut: "Ctrl+S" },
    { type: "item", label: "Save As...", shortcut: "Ctrl+Shift+S" },
    { type: "item", label: "Save All", shortcut: "Ctrl+K S" },
    { type: "separator" },
    { type: "item", label: "Close Editor", shortcut: "Ctrl+W" },
    { type: "item", label: "Close Folder" },
    { type: "separator" },
    { type: "item", label: "Exit" },
  ],
  Edit: [
    { type: "item", label: "Undo", shortcut: "Ctrl+Z" },
    { type: "item", label: "Redo", shortcut: "Ctrl+Y" },
    { type: "separator" },
    { type: "item", label: "Cut", shortcut: "Ctrl+X" },
    { type: "item", label: "Copy", shortcut: "Ctrl+C" },
    { type: "item", label: "Paste", shortcut: "Ctrl+V" },
    { type: "separator" },
    { type: "item", label: "Find", shortcut: "Ctrl+F" },
    { type: "item", label: "Replace", shortcut: "Ctrl+H" },
    { type: "item", label: "Find in Files", shortcut: "Ctrl+Shift+F" },
    { type: "item", label: "Replace in Files", shortcut: "Ctrl+Shift+H" },
  ],
  Selection: [
    { type: "item", label: "Select All", shortcut: "Ctrl+A" },
    { type: "item", label: "Expand Selection", shortcut: "Shift+Alt+Right" },
    { type: "item", label: "Shrink Selection", shortcut: "Shift+Alt+Left" },
    { type: "separator" },
    { type: "item", label: "Copy Line Up", shortcut: "Shift+Alt+Up" },
    { type: "item", label: "Copy Line Down", shortcut: "Shift+Alt+Down" },
    { type: "item", label: "Move Line Up", shortcut: "Alt+Up" },
    { type: "item", label: "Move Line Down", shortcut: "Alt+Down" },
  ],
  View: [
    { type: "item", label: "Command Palette...", shortcut: "Ctrl+Shift+P" },
    { type: "item", label: "Open View..." },
    { type: "separator" },
    { type: "submenu", label: "Appearance" },
    { type: "submenu", label: "Editor Layout" },
    { type: "separator" },
    { type: "item", label: "Explorer", shortcut: "Ctrl+Shift+E" },
    { type: "item", label: "Search", shortcut: "Ctrl+Shift+F" },
    { type: "item", label: "Source Control", shortcut: "Ctrl+Shift+G" },
    { type: "item", label: "Run", shortcut: "Ctrl+Shift+D" },
    { type: "item", label: "Extensions", shortcut: "Ctrl+Shift+X" },
    { type: "separator" },
    { type: "item", label: "Terminal", shortcut: "Ctrl+`" },
    { type: "item", label: "Problems", shortcut: "Ctrl+Shift+M" },
    { type: "item", label: "Output", shortcut: "Ctrl+Shift+U" },
    { type: "separator" },
    { type: "item", label: "Word Wrap", shortcut: "Alt+Z" },
  ],
  Go: [
    { type: "item", label: "Back", shortcut: "Alt+Left" },
    { type: "item", label: "Forward", shortcut: "Alt+Right" },
    { type: "separator" },
    { type: "item", label: "Go to File...", shortcut: "Ctrl+P" },
    { type: "item", label: "Go to Symbol in Workspace...", shortcut: "Ctrl+T" },
    { type: "item", label: "Go to Definition", shortcut: "F12" },
    { type: "separator" },
    { type: "item", label: "Go to Line/Column...", shortcut: "Ctrl+G" },
  ],
  Run: [
    { type: "item", label: "Start Debugging", shortcut: "F5" },
    { type: "item", label: "Run Without Debugging", shortcut: "Ctrl+F5" },
    { type: "item", label: "Stop Debugging", shortcut: "Shift+F5" },
    { type: "item", label: "Restart Debugging", shortcut: "Ctrl+Shift+F5" },
    { type: "separator" },
    { type: "item", label: "Open Configurations" },
    { type: "item", label: "Add Configuration..." },
  ],
  Terminal: [
    { type: "item", label: "New Terminal", shortcut: "Ctrl+`" },
    { type: "item", label: "Split Terminal", shortcut: "Ctrl+Shift+5" },
    { type: "separator" },
    { type: "item", label: "Run Task..." },
    { type: "item", label: "Run Build Task...", shortcut: "Ctrl+Shift+B" },
    { type: "item", label: "Run Active File" },
    { type: "separator" },
    { type: "item", label: "Show Running Tasks..." },
    { type: "item", label: "Terminate Task..." },
  ],
  Help: [
    { type: "item", label: "Welcome" },
    { type: "item", label: "Show All Commands", shortcut: "Ctrl+Shift+P" },
    { type: "item", label: "Documentation" },
    { type: "separator" },
    {
      type: "item",
      label: "Keyboard Shortcuts Reference",
      shortcut: "Ctrl+K Ctrl+R",
    },
    { type: "separator" },
    { type: "item", label: "Report Issue" },
    { type: "separator" },
    { type: "item", label: "About" },
  ],
};
